bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('social-auth/',
         include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]
# In this way, the Django development server will
# be in charge of serving the media files during
# development.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path

from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('ranking/', views.image_rankings, name='ranking'),
    path('', views.image_list, name='list'),
]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name='images_liked',
                                       blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Overriding the save method to set the
        slug field from title. When slug is not
        provided.
        """
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

bookmarks/images/forms.py
import urllib.request as urlrq
import certifi
import ssl
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.split('.')[-1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not '
                                        'match valid image extensions')
        return url

    def save(self, force_insert=False, force_update=False,
             commit=True):
        """
        Overriding the save method.
        1. create a new image instance by calling the save() method
        of the form with commit=False
        2. Get the url form the cleaned_data
        3. Generate a name of the image by combining the name and extension.
        4. Use the python urllib modeule to download the image and then call
        the save() method of the image field, passing it a ContentFile object
        that is instantiated with the downloaded file content.
        In this way you save the file to the media directory of your project.
        You pass save=False parameter to avoid saving the object to the
        database yet.
        5. In order to maintain the same behavior as the save() method we
        override, you save the form to the database only when the commit
        parameter is True.
        To use urllib to retrieve images served through https, we need to
        install certifi with pip.
        :param force_insert:
        :param force_update:
        :param commit:
        :return:
        """
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.split('.')[-1].lower()
        image_name = f'{name}.{extension}'

        # download the image from the given URL
        response = urlrq.urlopen(image_url, context=ssl.create_default_context(cafile=certifi.where()))
        image.image.save(
            image_name, ContentFile(response.read()),
            save=False
        )
        if commit:
            image.save()
        return image

bookmarks/images/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.conf import settings
import redis

from .forms import ImageCreateForm
from .models import Image
from bookmarks.common.decorators import ajax_required
from actions.utils import create_action

# redis connection
r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


@login_required
def image_create(request):
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # assign the current user to the form
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image added successfully')
            # redirect to the newly created item
            return redirect(new_item.get_absolute_url())
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request,
                  'images/image/create.html',
                  {'section': 'images',
                   'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # increment total image views by 1
    total_views = r.incr(f'image:{image.id}:views')
    # increment image ranking by 1
    # zincrby increment the score of value in sorted set name
    # by amount zincrby(name, amount, value)
    r.zincrby('image_ranking', 1, image.id)
    return render(request,
                  'images/image/detail.html',
                  {'section': 'images',
                   'image': image,
                   'total_views': total_views})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.user_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.user_like.remove(request.user)
                create_action(request.user, 'unlikes', image)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'error'})


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # If the request is AJAX and the page is out of range
            # return an empty page.
            return HttpResponse('')
        # If page is out of range deliver last page of results
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'selection': 'images', 'images': images})
    return render(request,
                  'images/image/list.html',
                  {'section': 'images', 'images': images})


# Not working
@login_required
def image_rankings(request):
    # get image ranking dictionary
    # According to redis doc negative count
    # returns all elements from the offset.
    # Here starting from 0 and using -1 we
    # want to retrieve all the element of image_ranking.
    # we also set desc=True to set result descending to true.
    image_ranking = r.zrange('image_ranking', 0, -1,
                             desc=True)[:10]
    # we create a list of ids, as image_ranking are not int
    image_ranking_ids = [int(id) for id in image_ranking]
    # get most viewed images and set it in a list.
    most_viewed = list(Image.objects.filter(
        id__in=image_ranking_ids
    ))
    # sort images based on index of image in image_ranking_ids
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request,
                  'images/image/ranking.html',
                  {'section': 'images',
                   'most_viewed': most_viewed})

bookmarks/images/templates/images/image/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Bookmark and Image{% endblock title %}

{% block content %}
<h1>Bookmark an Image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
</form>
{% endblock content %}

bookmarks/images/templates/images/image/detail.html
{% extends 'base.html' %}
{% block title %}{{ image.title }}{% endblock title %}

{% block content %}
<h1>{{ image.title }}</h1>
{% load thumbnail %}
<a href="{{ image.image.url }}">
<img src="{% thumbnail image.image 300x0 %}" class="image-detail"></a>
{% with total_likes=image.user_like.count users_like=image.user_like.all %}
<div class="image-info">
    <div>
        <span class="count">
            <span class="count">
            {{ total_views }} view{{ total_views|pluralize }}
            </span>
            <span class="total">{{ total_likes }}</span>
             like{{ total_likes|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}
        un{% endif %}like" class="like button">
            {% if request.user not in users_like %}
            Like
            {% else %}
            Unlike
            {% endif %}
        </a>
    </div>
    {{ image.description|linebreaks }}
</div>
<div class="image-likes">
    {% for user in users_like %}
    <div>
        <img src="{{ user.profile.photo.url }}">
        <p>{{ user.first_name }}</p>
    </div>
    {% empty %}
    No body likes this image yet.
    {% endfor %}
</div>
{% endwith %}
{% endblock %}
{% block domready %}
$('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
    {
        id: $(this).data('id'),
        action: $(this).data('action')
    },
    function(data){
        if (data['status'] == 'ok')
        {
            var previous_action = $('a.like').data('action');
            // toggle data action
            $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
            // toggle link text
            $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
            // update total likes
            var previous_likes = parseInt($('span.count .total'). text());
            $('span.count .total').text(previous_action == 'like' ? previous_likes + 1: previous_likes - 1);
        }
    }
    );
});
{% endblock domready %}

bookmarks/images/templates/images/image/list.html
{% extends 'base.html' %}
{% block title %}Images bookmarked{% endblock %}

{% block content %}
<h1>Images bookmarked</h1>
<div id="image-list">
    {% include 'images/image/list_ajax.html' %}
</div>
{% endblock content %}
{% block domready %}
{% comment %}
We define the following variables
page: stores the current page number.
empty_page: Allows you to know whether the user is on the last
page and retrieves an empty page. As soon as you get an empty page
you will stop sending additional AJAX requests because will assume
that there are no more results.
block_request: Prevents you from sending additional requests.

You use $(window).scroll() to capture the scroll event and also to
define a handler function.
You calculate the margin variable to get the difference between the 
total document height and the window height, because that's the height
of the remaining content for the user to scroll.
You subtract a value of 200 from the result so that you load the next
page when the user is closer than 200 pixels to the bottom of the page.
You only send an AJAX request if no other AJAX request is being done.
(block_request has to be false) and the user did not get to the last page
of results (empty_page is also false)
You set block_request to true to avoid a situation where the scroll event 
triggers additional AJAX requests, and increase the page counter by one,
in order to retrieve the next page.
You perform an AJAX GET request using $.get() and receive the HTML response in
a variable called data. There are two scenarios.
The response has no content: You got to the end of the results, and there are not
more pages to load. You set empty_page to true to prevent additional AJAX request.
The response contains data: You append the data to the HTML element with the 
image-list ID. The page content expands vertically, appending results when the user 
approaches the bottom of the page.
{% endcomment %}
var page = 1;
var empty_page = false;
var block_request = false;

$(window).scroll(function(){
    var margin = $(document).height() - $(window).height() - 200;
    if ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
        block_request = true;
        page += 1;
        $.get('?page=' + page, function(data){
            if(data == ''){
                empty_page = true;
            }
            else {
                block_request = false;
                $('#image-list').append(data);
            }
        });
    }
});
{% endblock domready %}

bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% for image in images %}
<div class="image">
    <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{ image.get_absolute_url }}">
            <img src="{{ im.url }}">
        </a>
    </a>
    <div class="info">
        <a href="{{ image.get_absolute_url}}" class="title">
            {{ image.title }}
        </a>
    </div>
</div>
{% endfor %}

bookmarks/images/templates/images/image/ranking.html
{% extends 'base.html' %}

{% block title %}Image ranking{% endblock title %}

{% block content %}
<h1>Images Ranking</h1>
<ol>
    {% for image in most_viewed %}
    <li>
        <a href="{{ image.get_absolute_url }}">{{ image.title }}</a>
    </li>
    {% endfor %}
</ol>
{% endblock content %}